export const VARSITY = [
  { name: "Sarah Wright", cap: "1", isGoalie: true },
  { name: "Grace Smalley", cap: "1A", isGoalie: true },
  { name: "Giselle Sanchez", cap: "2" },
  { name: "Taylor Chestnut", cap: "3" },
  { name: "Tess Schirmer", cap: "4" },
  { name: "Josie Haast", cap: "5" },
  { name: "Ainsley Swann", cap: "6" },
  { name: "Clara O'Connor", cap: "7" },
  { name: "Clara Peterson", cap: "8" },
  { name: "Delilah Ricketts", cap: "9" },
  { name: "Emi Haast", cap: "10" },
  { name: "Quinn Arroyo", cap: "11" },
  { name: "Lillie Trapenese", cap: "12" },
  { name: "Reagan Fullerton", cap: "13" },
  { name: "Kiley Arroyo", cap: "14" },
  { name: "Kayden Page", cap: "15" },
  { name: "Montana Topping", cap: "18" },
];

export const JV = [
  { name: "Gabriela Glueck", cap: "1", isGoalie: true },
  { name: "Landyn Dickerson", cap: "2" },
  { name: "Melia Wijesinghe", cap: "3" },
  { name: "Phaley Kim", cap: "4" },
  { name: "Claire Sullivan", cap: "5" },
  { name: "Addie Stanton", cap: "6" },
  { name: "Mia Jenkins", cap: "7" },
  { name: "Ava Esposito", cap: "8" },
  { name: "Meghan Torres", cap: "9" },
  { name: "Meghan Condon", cap: "10" },
  { name: "Molli Colclasure", cap: "11" },
  { name: "Maxine De Lusong", cap: "12" },
  { name: "Leila Wijesinghe", cap: "13" },
  { name: "Sadie Inman-Sumerau", cap: "14" },
  { name: "Olivia Kuss", cap: "15" },
  { name: "Marley Flores", cap: "16" },
  { name: "Nola Scotto", cap: "17" },
  { name: "Daphne Ertoz", cap: "18" },
];
